config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions

  resources :articles do
    resources :comments
  end
  get 'welcome/index'

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 5}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  private
  def current_user
    @current_user=session[:user_id] if session[:user_id]
  end
  helper_method :current_user
  def authorize
    if current_user.nil?
      redirect_to new_session_path, alert: "Not Authorized"
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :authorize, only: [:new, :edit, :update, :destroy]

  def index
    @articles=Article.all
  end

  def new
    @article=Article.new
  end

  def edit
    @article=Article.find(params[:id])
  end

  def create
    @article=Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article=Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def show
    @article=Article.find(params[:id])
  end

  def destroy
    @article=Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title,:text)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :authorize, only: [:destroy]

  def create
    @article=Article.find(params[:article_id])
    @comment=@article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article=Article.find(params[:article_id])
    @comment=@article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter,:body)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user=User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id]=user.id
      redirect_to root_url, notice: "Logged In!"
    else
      flash.now.alert = "Email or password incorrect"
      render 'new'
    end
  end

  def destroy
    session[:user_id]=nil
    redirect_to root_url, notice: "Logged Out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user=User.new
  end
  def create
    @user=User.new(user_params)
    if @user.save
      redirect_to root_url, notice: "Thank You for Signing Up"
    else
      render 'new'
    end
  end
  private
  def user_params
    params.require(:user).permit(:email,:password,:password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

    <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.submit %>
    </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>
  <%= @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article_path(article), method: :delete, data: {confirm: 'Are You Sure?'} %></td>
      </tr>
<% end %>
</table>
<%= link_to 'Back', welcome_index_path %>

app/views/articles/new.html.erb
<h1>New article</h1>
 <%= render 'form' %>
 <%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<p>
  <td><%= link_to 'Delete Comment',[comment.article, comment], method: :delete, data: {confirm: 'Are You Sure?'} %></td>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
    <p>
      <%= f.label :commenter %><br>
      <%= f.text_field :commenter %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Try2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
    <div class="user_header">
      <% if current_user %>
          Logged in
          <%= link_to "Logout", session_path("AS"), method: :delete %>
      <% else %>
        <%= link_to 'Sign Up', new_user_path %> or
        <%= link_to 'Log In', new_session_path %><br>
      <% end %>
    </div>
  </div>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
        <h2>Form is Invalid</h2>
        <div class="error_messages">
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <p>
        <%= f.label :email %><br>
        <%= f.text_field :email %>
      </p>
    </div>
    <div class="field">
      <p>
        <%= f.label :password %><br>
        <%= f.password_field :password %>
      </p>
    </div>
    <div class="field">
      <p>
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation %>
      </p>
    </div>
    <div class="action">
      <%= f.submit %>
    </div>
<% end %>

app/views/welcome/index.html.erb
<h1>Hello Rails!</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<%= link_to 'My Blog', controller: 'articles' %>
<%= link_to 'New Article', new_article_path %>